### ISSUE TITLE
Javelin broke

### ISSUE THREAD

**Issue by Lulalaby** [Aiko-IT-Systems/Phabricator#23]
Apparently javelin broke for whatever reason:

```js
Uncaught ReferenceError: JX is not defined
    <anonymous> https://cdn.aitsys.dev/res/1692989274T/fontsizeplusoneX/phabricator/90777e84/core.pkg.js:26
[core.pkg.js:26:1](https://cdn.aitsys.dev/res/1692989274T/fontsizeplusoneX/phabricator/90777e84/core.pkg.js)
Uncaught ReferenceError: JX is not defined
    <anonymous> https://cdn.aitsys.dev/res/1656174913T/fontsizeplusoneX/phabricator/a8fb6a46/differential.pkg.js:12
[differential.pkg.js:12:1](https://cdn.aitsys.dev/res/1656174913T/fontsizeplusoneX/phabricator/a8fb6a46/differential.pkg.js)
Uncaught ReferenceError: JX is not defined
    <anonymous> https://cdn.aitsys.dev/res/1692989274T/fontsizeplusoneX/phabricator/c412d576/rsrc/js/core/behavior-form-file-validation.js:6
[behavior-form-file-validation.js:6:1](https://cdn.aitsys.dev/res/1692989274T/fontsizeplusoneX/phabricator/c412d576/rsrc/js/core/behavior-form-file-validation.js)
Uncaught ReferenceError: JX is not defined
    <anonymous> https://cdn.aitsys.dev/res/1654045397T/fontsizeplusoneX/phabricator/187792c2/dark-console.pkg.js:13
```

Might need to be fixed here: https://github.com/aiko-IT-Systems/javelin 
But I forgot how it works, so gotta figure that out first.

Due to it broken, no dropdown / popouts work anymore

```[tasklist]
### Tasks
- [ ] Figure out how javelin is injected
- [ ] Figure out why it broke
- [ ] Fix dependencies
- [ ] Rebuild on aitsys.dev
- [ ] Test
- [ ] Merge
```
